name: CI
on:
  push:
    branches:
      - master
  workflow_dispatch:
permissions:
  packages: read

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.commits[0].message, '[ci-skip]')"
    env:
      MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
      HANGAR_API_KEY: ${{ secrets.HANGAR_API_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GIT_COMMIT_MESSAGE: ${{ join(github.event.commits.*.message, '<br>') }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - name: Set up JDK 21
        uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5
        with:
          java-version: 21
          distribution: 'adopt'
      - name: Build and Publish to Modrinth
        run: |
          ./gradlew modrinth --stacktrace
      - name: Build and Publish to Hangar
        run: |
          ./gradlew publishPluginPublicationToHangar
